### ISSUE TITLE
Error al facturar con descuento

### ISSUE THREAD

**Issue by Gabrielnik** [wnpower/iFactura-WHMCS#10]
Hola!

Utilizo un plugin en Woocommerce para ofrecer un descuento por pago por transferencia.
Es Woo Payment Descount

Las ventas realizadas con esa modalidad presentan este error al intentar facturar desde Woocommerce

No se puede calcular el descuento global sobre los productos dado que el descuento no esta aplicado sobre los impuestos tambien. Por ende no se puede calcular el IVA verdadero.1422

Cómo se podría solucionar? Gracias!

![Error Facturación](https://user-images.githubusercontent.com/80854236/111530663-534bcd00-8742-11eb-95c2-ca67c832267b.jpg)

**Comment by villaboamiguel** [comment]
Hola! este repositorio es para el plugin de WHMCS. El que vos buscas es el de Woocommerce: https://github.com/fedealvz/Woo-iFactura

Igualmente ese asunto ya lo vimos en ese repo y se trato en este issue: https://github.com/fedealvz/Woo-iFactura/issues/19

Saludos!
