### ISSUE TITLE
Problema con facturas

### ISSUE THREAD

**Issue by scaetano84** [wnpower/iFactura-WHMCS#19]
Hola, actualmente tengo un módulo que genera un recargo al pagar mediante Mercadopago (por su comisión alta).
El problema con iFACTURA es que envía solo este recargo a facturar y no el costo del servicio. Adjunto imagen con ejemplo
![ejemploiFACTURA](https://user-images.githubusercontent.com/75219283/132565519-e19fc793-c483-4023-a432-8280aeb83c99.png)

Muchas gracias.

**Comment by villaboamiguel** [comment]
Hola!
No termino de entender que es lo que no ves.  Por la imagen que adjuntas veo un item  "servidor" y un item "recargo" como facturados, que por lo que te entendí que cobran un recargo cuando se utiliza Mercadopago.

Si ese "recargo" se calcula/aplica con un addon externo a las funcionalidades de WHMCS tendrías que revisar o consultar como aplica el mismo sobre la invoice. El plugin de iFactura factura todas las líneas de detalle que se encuentran en una invoice, con los textos como figuran en cada item.

Saludos!

**Comment by scaetano84** [comment]
Hola, como se ve en la factura, no está tomando el IVA del monto de $17019.83 solo lo hace en el recargo de Mercadopago.

**Comment by villaboamiguel** [comment]
Ahora si te entendí, por el mensaje sonaba a algo del recargo puntualmente dado que no menciona el IVA.

Fijate en la invoice en cuestión si tienen los elementos el campo tildado "Taxed" o "Impuestos". Adjunto captura de como se ve:
![image](https://user-images.githubusercontent.com/74683362/132573627-0a8bb544-ed86-4e74-ad67-8859200109ab.png)

Si dicho campo no esta tildado no se aplican impuestos sobre dicho campo y puede ser el caso.

Saludos

**Comment by scaetano84** [comment]
Perfecto, ahí lo activé. De esta forma se factura igual para AFIP y es solo un tema estético? Gracias.

**Comment by villaboamiguel** [comment]
Si el campo esta tildado antes de enviar la invoice a iFactura se calcula el IVA. Como en el caso de la captura que enviaste no estaba tildado, el IVA no se procesa. 

Como una recomendación, fijate en la configuración del producto si esta configurado para que tenga impuestos así cuando se generen otras invoices más adelante tengan los impuestos. Adjunto captura de como se ve:
![image](https://user-images.githubusercontent.com/74683362/132577553-d4b9942d-709c-4969-9ae7-e548ad2d7bd2.png)

Ojo que ese campo es ignorado si el cliente al que se le hace la invoice tiene tildado la excepción de impuestos.

Saludos

**Comment by scaetano84** [comment]
Buenas, no, justamente con ese error aprendi! jajaj. Te adjunto el servicio
![github4](https://github.com/wnpower/iFactura-WHMCS/assets/75219283/3aaa6b4f-6297-4835-80fd-21fedd7aa91f)
