### ISSUE TITLE
No se genera la factura en WHMCS

### ISSUE THREAD

**Issue by stefanofabi** [wnpower/iFactura-WHMCS#20]
Hola! migré el sitio de whmcs a un servidor vps, todo sigue igual solo que el modulo no genera la factura automáticamente, me las deja listadas en el modulo y las tengo que ir emitiendo manualmente.

¿Que puede ocurrir? ¿Donde puedo ver algún log?

Utilizo WHMCS 8.3.1 y PHP 7.4

**Comment by villaboamiguel** [comment]
Si las creas a mano tenes que usar el botón "Publish and Send Email". El módulo esta enganchado al evento de la generación de la invoice con el envió del correo. Si presionás en solo "Publish" la automatización no va a funcionar. 

![image](https://user-images.githubusercontent.com/74683362/142038119-910add94-3eee-48f3-bd7b-c26b55c3e0e9.png)

Saludos

**Comment by stefanofabi** [comment]
La factura no la emito yo, la hace el mismo cron de WHMCS.

**Comment by villaboamiguel** [comment]
Si la generás manualmente te queda en Draft, es necesario presionar en "Publish and Send Email" para que haga el envío a iFactura. Hice esa prueba hoy en un entorno con las mismas versiones que vos y funciona correctamente. 

Que otros plugins o modificaciones tenes en tu WHMCS?
Tenes los clientes configurados para que no se les envíen los emails? porque de ser así cuando se genera la invoice, no se enviá el mail y no se enviá de forma automática a iFactura. 

Otra cosa que te puedo sugerir es en la configuración de WHMCS, solapa "Others", activar el Debug para hooks y addons.
![image](https://user-images.githubusercontent.com/74683362/142082257-d15334c3-eaff-4307-ba4d-eb6650133d74.png)
Con esto activado anda al log del sistema y fijate si ves lo siguiente:
![image](https://user-images.githubusercontent.com/74683362/142082557-06a5f0cc-4bc1-4aff-b56e-011d9093186c.png)

Saludos.

**Comment by stefanofabi** [comment]
Solamente tengo unas pasarelas de pago como MercadoPago, Criptomonedas, TodoPago, etc. que no interfieren.

Este es el Debug Hook Mode

![ifactura log](https://user-images.githubusercontent.com/47072123/142133684-d85d524c-82b6-492d-b7e6-06ce961c93fb.png)

Aqui va un caso real, se generó un pedido de un cliente ya con sus datos confirmados y verificados. Este fue el resultado

![datos cliente](https://user-images.githubusercontent.com/47072123/142133681-9ebed60e-8e38-4d78-9d24-354c4c304ee6.png)

![invoice sin factura](https://user-images.githubusercontent.com/47072123/142133686-7ad0012d-2f33-4fe1-a377-e1a18943a1e9.png)


Como ve en la foto no se genero la factura. Aclaro que si voy al listado de invoice sin facturas y la emito manualmente todo funciona correctamente, lo que parece no funcionar es el hook.

**Comment by villaboamiguel** [comment]
Estuve probando creando un nuevo cliente con un servicio nuevo que venza el 23/11/21 y configurar para que se hagan las invoices 7 dias antes del Next Due Date. Ejecutando el cron diario funciona correctamente el hook.

El usuario que tenes configurado como "Usuario API" para el addon de iFactura es válido? Por defecto es admin pero si le cambiaste el nombre al admin puede estar por ahí el problema.

Que diferencias podes tener de configuración con respecto a tu entorno anterior? Tanto a nivel WHMCS o Servidor. 

Otra sugerencia, es que ejecutes el cron con el parámetro **-vvv** para ver el máximo verbose de la salida del cron para si hay algún error o algo que no estemos viendo.

Saludos

**Comment by villaboamiguel** [comment]
Otra cosa, cualquier mensaje que deje el hook de iFactura en la bitacora del sistema lo podes encontrar que comienza con el siguiente texto 
```
[iFactura Addon Module Hook]
```

Me había equivocado y el string para buscar en el log que te dije anteriormente es solo para la ejecución manual desde el addon.

**Comment by stefanofabi** [comment]
El usuario api es el mismo usuario que estoy usando en whmcs.

Algunas diferencias entre el alojamiento cpanel que tenia antes y el vps Ubuntu:
- Configuré CloudFlare de extremo a extremo (proxy activado)
- Justo antes de migrar actualicé whmcs a la v8.3.1
- Si realizo un ping desde el vps a app.ifactura.com.ar me responde con la ipv6
- Distinta ip y directorio de instalación

No veo mas diferencias. 

Algun problema de permisos quizás en la instalación?

**Comment by villaboamiguel** [comment]
Por la IP, dominio, cloudflare no veo problemas allí. Además que si las haces manualmente funcionan. Por lo que veo tambien en tu log del hook funcionan las notas de cancelación de manera automática y algunas de creación. 

Por ejemplo la invoice número 11039, la hiciste manualmente y publicaste o fue automática?

La recomendación del -vvv es para que lo pongas en el cron asi ves todo el proceso. La parte de generación de invoices solo se ejecuta 1 vez por dia en el horario que hayas definido como daily. Ahora si lo queres forzar a hacer eso solo podes usar los argumentos

```
do --CreateInvoices -vvv
```

**Comment by stefanofabi** [comment]
La invoice #11039 es de un cliente que generó un pedido a través del carrito de compras. 

Ahora agrego el parametro -vvv al crontab y veré mañana que resultados trae.

**Comment by villaboamiguel** [comment]
Dale, en ese caso deberías ver algo así si se generan invoices.
![image](https://user-images.githubusercontent.com/74683362/142268386-4fde227f-7db7-46f3-9993-4f0ebab8fbd8.png)

El hook estaría funcionando si se creo la factura cuando se hizo la venta. Tiene que haber algún parámetro de configuración del cliente, del producto o de la configuración del cron que se nos esta escapando.

**Comment by stefanofabi** [comment]
Si.. Definitivamente es algo del cron porque he probado también utilizar el botón "Facturar servicios seleccionados" y la factura se genera con la invoice perfectamente.


Una cosa que no entendí, agregué en crontab -e el parametro -vvv a la ruta del script pero esto se ejecuta en segundo plano automáticamente, como vería yo la salida de ese script mañana en el daily cron de las 9AM?

**Comment by villaboamiguel** [comment]
Hace que guarde el standard output y el standard error en un archivo y después pasado ese horario podes chequear el contenido. Agregando algo así al final de la lineá del comando por ejemplo
`>>/var/www/clientes.4evergaming.com.ar/log.txt 2>&1`

**Comment by stefanofabi** [comment]
Este seria el log, entre la 01:00a.m y las 13:55Hs. del dia 22/11

[log.txt](https://github.com/wnpower/iFactura-WHMCS/files/7582916/log.txt)

**Comment by villaboamiguel** [comment]
No veo que crashie ni informe de algún error. Tampoco indica si se genero alguna invoice en la ejecución.

**Comment by stefanofabi** [comment]
Lo solucioné!

Cuestión que había un problema entre el certificado ssl viejo de cpanel y el nuevo certificado CA de CloudFlare.

**Comment by villaboamiguel** [comment]
Gracias por el comentario de como lo solucionaste para tener en cuenta. Saludos!
