### ISSUE TITLE
genera aleatoriamente factura automáticamente desde WHMCS

### ISSUE THREAD

**Issue by cinbus** [wnpower/iFactura-WHMCS#22]
Hola, los contacto porque ahora no está generando facturas automáticamente desde el WHMCS siendo que el cliente se encuentra tildado los campos de "facturar" y "datos confirmados", sin embargo hoy sí generó otra factura pero este no lo genera, tampoco veo nada reportado en el visor de eventos. A qué se debe la no generación?

datos de cliente:
FERNANDEZ,CARLOS ALBERTO
20084731030
RI

gracias

Cinthia

**Comment by villaboamiguel** [comment]
Hola!

Esa invoice si vas al Addon de iFactura esta en el listado para emitirla manualmente? Que fecha de emisión tiene dicha invoice?

Saludos

**Comment by cinbus** [comment]
no aparece listada tampoco en el addon de iFactura, la fecha que fue lanzado el proceso para generar la factura fue hoy a las 10AM

**Comment by villaboamiguel** [comment]
Bien, al no figurar ahi significa que no cumple alguna condición.
Sos responsable inscripto? De ser asi, revisa que la invoice en cuestión tenga sus elementos facturados con el tilde de "Taxed". 
![image](https://user-images.githubusercontent.com/74683362/145445198-33f2c9de-76fc-4c82-b2d0-913319ebdc25.png)
Y el tax rate de la invoice sea mayor a 0
![image](https://user-images.githubusercontent.com/74683362/145445274-0b99d42b-ff07-4336-ad7e-f3e12d423047.png)
Tambien es importante que el cliente no tenga el tilde de "Tax Exempt"
![image](https://user-images.githubusercontent.com/74683362/145445340-68de7e58-66fe-48e9-b2ac-3a634f905618.png)

Para más información sobre dichos campos te recomiendo ver los demás issue de este repositorio porque es un tema que se suele hablar y comentar de como configurar para cada caso de condición impositiva.

Saludos!

**Comment by cinbus** [comment]
gracias!! :)
no tenía tildado el impuesto el cliente.. corregido.. pero no aparece listado como pendiente en el addon.. será q como ya la cargó sin IVA no va a generar la factura?

**Comment by villaboamiguel** [comment]
Si la invoice se genero sin impuestos y al ser vos Responsable inscripto, el módulo no va a poder calcular bien los impuestos (IVA). Por eso el módulo no la ve para facturar manualmente.

**Comment by cinbus** [comment]
comprendido!
