### ISSUE TITLE
Error decode IonCube 12

### ISSUE THREAD

**Issue by stefanofabi** [wnpower/iFactura-WHMCS#26]
Hola. Necesito el Módulo para que trabaje con WHMCS 8.6.0 y Ion Cube 12.

**Comment by villaboamiguel** [comment]
Hola!
Tenemos probado el caso con IonCube 12 con PHP 7.4. Si estas teniendo algún problema o código de error al momento de abrir necesito más detalles sobre el mismo para ver por dónde va la cuestión.

Saludos

**Comment by stefanofabi** [comment]
Con PHP 8.1 lo necesito, por favor.

Gracias

**Comment by villaboamiguel** [comment]
Hola,
Encontramos algunas diferencias en IonCube cuando trabaja con PHP 8.1. Hay un nuevo release compatible con WHMCS 8.6, PHP 8.1 y IonCube 12 disponible que podes comenzar a usar. La versión 2.10.0. 

Gracias por el feedback,
Saludos
