### ISSUE TITLE
{{FacturaAFIP=C0A7A42175C3F20540F3E615A1264D0F}}

### ISSUE THREAD

**Issue by alerickert** [wnpower/iFactura-WHMCS#29]
Al momento de poner el código de notas al entrar al modo html y tambien pdf, aparece asi {{FacturaAFIP=C0A7A42175C3F20540F3E615A1264D0F}}

en vez del link para ver la factura.

**Comment by villaboamiguel** [comment]
Hola!,
Revisaste tener el código como figura en el README? 
https://github.com/wnpower/iFactura-WHMCS#customizaciones

Así lo tengo andando en un WHMCS 8.6.1 con el cambio sugerido aplicado. 
![image](https://user-images.githubusercontent.com/74683362/224763490-8f7ccdba-7a1a-4822-8a4b-0f90352124e2.png)
Si tenes un WHMCS 8.0 o mayor tenes 2 themes para el área de cliente, fíjate de tener aplicado el cambio en el theme que tengas activado. Esa captura es del theme "twenty-one".

Saludos
