### ISSUE TITLE
Versión del módulo

### ISSUE THREAD

**Issue by stefanofabi** [wnpower/iFactura-WHMCS#3]
Hola, descargo e instalo el último release y en whmcs sigue apareciendo v2.7.4

A qué se debe esto?

**Comment by WNPowerStaff** [comment]
Hola @stefanofabi te confirmo que es un TYPO y no afecta al funcionamiento del addon module.
Ya está reportado y será corregido en el próximo release!

**Comment by WNPowerStaff** [comment]
Solucionado en https://github.com/wnpower/iFactura-WHMCS/releases/tag/V2.9.0
