### ISSUE TITLE
Request Timeout a los 4 minutos para acceder al addon

### ISSUE THREAD

**Issue by jmzolezzi** [wnpower/iFactura-WHMCS#30]
Estimados, publico acá el issue que tenemos en el addon para ver si alguien mas se le ocurre que puede ser.

Hace rato vengo subiendo el max_execution_time, pero ahora el addon me esta dando Request Timeout a los 4 minutos, y quisiera arreglar el problema de fondo en lugar de continuar subiendo el limite.

¿Qué es lo que se ejecuta al visitar addonmodules.php?module=ifactura_afip?
Tal vez tengamos que limpiar algo dentro de nuestro WHMcs ya que asumo, no es normal en absoluto.

Gracias!

**Comment by dservin75** [comment]
Hola, me pasa lo mismo. Como lo solucionaste? gracias!
