### ISSUE TITLE
Soporte para PHP 8.2

### ISSUE THREAD

**Issue by jmzolezzi** [wnpower/iFactura-WHMCS#36]
Aprovechando que la última versión de WHMcs soporte PHP 8.2, sería genial poder usar iFactura con dicha versión.

**Comment by fedealvz** [comment]
Hola Juan!!! Cómo estás?
Listo con el update, lo podés descargar de releases: https://github.com/wnpower/iFactura-WHMCS/releases/tag/v2.10.1

Abrazo!

**Comment by jmzolezzi** [comment]
Impecable Fede, muchisimas gracias!!
