### ISSUE TITLE
deja de facturar despues del cambio de monotributo a ri

### ISSUE THREAD

**Issue by gmsastre** [wnpower/iFactura-WHMCS#4]
Hola buenos dias, estoy con un inconveniente en la generación de facturas desde whmcs, desde que realice el cambio de monotributo a RI no me genera ni ve ninguna factura. Hace minuto por indicacion del soporte telefonico que me asistió, me pidio que genere una fc manualmente desde el panel de control de ifactura para descartar un problema de mi cuit, pero se envio correctamente. Por lo tanto deberiamos centrar la atencion en el modulo instalado en whmcs.
Aclaro que esto lo vengo utilizando normalmente como monotributista todo cambio desde que inicie las operaciones como RI.

Por otro lado quisiera saber lo siguiente en cuanto a la facturacion:
- Si yo genero una factura de servicio a un cliente RI, en WHMCS genero el comprobante interno sin IVA, y luego cuando pasa a ifactura uds le agregan el IVA? O sea no lo deberia agregar yo en WHMCS pq luego uds tambien agregarian IVA sobr el monto final? Necesito confirmacion de dicha operativa.

Ademas con los exentos o monotributistas, donde el iva no se discrimina por lo tanto va incluido en el costo del servicio, como trabaja ifactura en ese caso? lo suma al monto facturado sin discriminarlo?

Saludos! Gustavo

**Comment by villaboamiguel** [comment]
Hola!

Tenes configurado los impuestos o taxes en tu WHMCS?. Me paso cuando cambie a Responsable inscripto que tenia mi WHMCS configurado sin impuestos y no aparecían en el módulo ni se hacían solas. Esto se ve que es necesario para que iFactura calcule el IVA.

Así lo tengo configurado: 
![image](https://user-images.githubusercontent.com/74683362/99586515-9e3d1a00-29c6-11eb-929c-75efa8d658c2.png)

Una vez hecho esto te va a generar las invoices con impuestos y ahí si modulo las empezó a encontrar. Así queda una invoice con los impuestos correctamente configurados.
![image](https://user-images.githubusercontent.com/74683362/99586782-ee1be100-29c6-11eb-9319-a7f5e4a2e628.png)

Siendo responsable inscripto le tenes que cobrar el IVA a todos, La diferencia esta en que a los Responsables Inscriptos les tenés que desglosar el IVA, al resto no se le muestra eso pero se factura dentro del total del comprobante.

Saludos!

**Comment by gmsastre** [comment]
Muchas gracias Miguel, era eso!
