### ISSUE TITLE
whmcs no encuentra invoice a facturar

### ISSUE THREAD

**Issue by gmsastre** [wnpower/iFactura-WHMCS#5]
Recientemente pase de monotributo a ri y esto hizo que en varios clientes se generara la invoice sin el IVA, entonces tuve que cancelar la factura y volver a facturar el servicio con IVA, el problema que tengo es que cuando realizo la facturacion del servicio y luego  voy al panel de ifactura para poder realizar la facturacion manual, no me aparece ninguna factura para mandar a ifactura. Que estoy haciendo mal? 
Saludos.

**Comment by villaboamiguel** [comment]
Hola!
Las cosas que checkeo cuando me falta alguna invoice son:
* Tener el tilde en facturar y en datos confirmados en el perfil del cliente
* Que tenga taxes la invoice.
![image](https://user-images.githubusercontent.com/74683362/99891641-e9fff580-2c4a-11eb-9b52-440039653b7a.png)
* Que mes y año tiene configurado el módulo de iFactura en WHMCS. Dichos campos son para buscar invoices cuya fecha sea 
posterior a dichos campos.

Saludos!

**Comment by WNPowerStaff** [comment]
Corrección del filtro de fechas del dashboard corregida en https://github.com/wnpower/iFactura-WHMCS/releases/tag/V2.9.0
