### ISSUE TITLE
WHCMS no me importa las facturas a Ifactura.

### ISSUE THREAD

**Issue by Nexolife** [wnpower/iFactura-WHMCS#6]
Hola, intenté todos los pasos anteriormente dichos en el repositorio y no me funciona aún. Intenté con 5 usuarios e hicieron el pago y no fueron exportadas. Por favor necesito ayuda para resolver este problema. Dejo 2 capture de los pagos y el módulo de IFactura

![Captura de pantalla 2021-02-23 a las 10 35 38 a m](https://user-images.githubusercontent.com/79521948/108851165-e4f07080-75c2-11eb-8bbf-49a1528d5703.png)

![Captura de pantalla 2021-02-23 a las 10 32 14 a m](https://user-images.githubusercontent.com/79521948/108851112-d86c1800-75c2-11eb-910b-cebd67f0a9cf.png)

**Comment by villaboamiguel** [comment]
Hola!
Te pido por favor si me enviás una captura de una invoice y me confirmes tu condición impositiva.  
Los perfiles de los clientes tienen tildados los campos "Facturar" y "Datos confrmados"? Dichos campos hacen elegibles a las invoices de esos clientes.

En esa vista que ves en la primera captura vas a ver invoices que están aptas para ser enviadas a iFactura si es que ya no se enviaron antes.

Saludos!

**Comment by villaboamiguel** [comment]
Acá tenes otro issue con la misma problemática y los pasos a verificar en WHMCS:
https://github.com/wnpower/iFactura-WHMCS/issues/5

**Comment by Nexolife** [comment]
Hola, revisé todo lo que dijiste e hicimos dos pagos para hacer pruebas e igualmente no me hace la exportación, Te dejo 2 screen
![Captura de pantalla 2021-02-23 a las 11 29 47 a m](https://user-images.githubusercontent.com/79521948/108858370-d908ac80-75ca-11eb-8eaa-89283df2ac96.png)
![Captura de pantalla 2021-02-23 a las 11 26 11 a m](https://user-images.githubusercontent.com/79521948/108858379-dad27000-75ca-11eb-8cf5-e9c51d66ec53.png)

**Comment by Nexolife** [comment]
Yo soy responsable inscrito

**Comment by Nexolife** [comment]
Sería esta?
![Captura de pantalla 2021-02-23 a las 12 35 20 p m](https://user-images.githubusercontent.com/79521948/108867111-9c8d7e80-75d3-11eb-87ba-dac9a378532e.png)

**Comment by villaboamiguel** [comment]
Esto necesito:
![image](https://user-images.githubusercontent.com/74683362/108869244-c5167800-75d5-11eb-9ce8-f5813849cd83.png)
Es una captura de un WHMCS de un responsable inscripto que tiene configurado el 21% de IVA en los productos y se facturan en las invoices. Lo saque del issue que te nombre antes #5 

Entiendo que si no tenes configurados los impuestos en WHMCS y tenes el perfil del cliente con los checks de "Datos confirmados" y "Facturar" bien tiltados. Tu problema estaría ahí en los impuestos, por eso te pido la captura de pantalla para confirmar esto.

**Comment by Nexolife** [comment]
Estaba de esta manera. Dónde puedo configurar los impuestos?


![Captura de pantalla 2021-02-23 a las 12 58 34 p m](https://user-images.githubusercontent.com/79521948/108870418-dc099a00-75d6-11eb-9a6e-4225f03cfb02.png)

**Comment by villaboamiguel** [comment]
Los impuestos de esa invoice parecen bien. Me podes mostrar el estado, fecha de emisión y campo notas de esa invoice y confirmar que ese cliente tiene tildados "datos confirmados" y "facturar".

Gracias

**Comment by Nexolife** [comment]
![Captura de pantalla 2021-02-23 a las 1 11 06 p m](https://user-images.githubusercontent.com/79521948/108872133-9ea60c00-75d8-11eb-9bed-5ac31fe4e570.png)

**Comment by Nexolife** [comment]
![Uploading Captura de pantalla 2021-02-23 a las 1.12.29 p.m..png…]()

**Comment by Nexolife** [comment]
![Captura de pantalla 2021-02-23 a las 1 12 29 p m](https://user-images.githubusercontent.com/79521948/108872365-dd3bc680-75d8-11eb-8117-2309d814f8fb.png)

**Comment by villaboamiguel** [comment]
No se ve el campo notas. Se ve que no la termino de subir.

Proba lo siguiente: anda a la configuración del módulo y en el año y mes de comienzo para facturar ponelo en ninguno.
![image](https://user-images.githubusercontent.com/74683362/108873178-ad40f300-75d9-11eb-9744-e3fa2443da9c.png)

A ver si tiene problemas con las fechas. En caso de que las empieces a ver me podrías confirmar que versión de WHMCS tenes?

Gracias!

**Comment by Nexolife** [comment]
![Captura de pantalla 2021-02-23 a las 1 40 31 p m](https://user-images.githubusercontent.com/79521948/108876205-be3f3380-75dc-11eb-89d4-96285475f87b.png)

**Comment by Nexolife** [comment]
![Captura de pantalla 2021-02-23 a las 1 42 35 p m](https://user-images.githubusercontent.com/79521948/108876472-02cacf00-75dd-11eb-9837-d5c524749420.png)

**Comment by Nexolife** [comment]
Hola, ahora estoy teniendo este problema
![Captura de pantalla 2021-02-23 a las 1 57 21 p m](https://user-images.githubusercontent.com/79521948/108878481-11b28100-75df-11eb-8eec-28899bac8247.png)

**Comment by villaboamiguel** [comment]
Fijate si funciona ahora con las fechas puestas en ninguna por favor.

**Comment by Nexolife** [comment]
Ya me lo toma pero ahora me da ese error
![Captura de pantalla 2021-02-23 a las 3 29 04 p m](https://user-images.githubusercontent.com/79521948/108890096-e7b38b80-75eb-11eb-982c-3bb5ba185d1d.png)
![Captura de pantalla 2021-02-23 a las 3 29 12 p m](https://user-images.githubusercontent.com/79521948/108890089-e5e9c800-75eb-11eb-8a18-ca496efa5d40.png)

**Comment by villaboamiguel** [comment]
Ahí tenes que revisar los datos de inicio de sesión de iFactura en el módulo de WHMCS. Fijate que si copias y pegas la password no contenga caracteres demás y que los mismos funcionen en app.ifactura.com.ar

**Comment by Nexolife** [comment]
Gracias, ya recibo!
