### ISSUE TITLE
Facturas no se emiten al AFIP

### ISSUE THREAD

**Issue by Nexolife** [wnpower/iFactura-WHMCS#7]
Hola, ya las facturas llegan de WHMCS a IFactura pero no se emiten a el AFIP, qué error podría estar teniendo?
![Captura de pantalla 2021-02-24 a las 10 15 56 a m](https://user-images.githubusercontent.com/79521948/109006176-8e019e80-7689-11eb-9a13-dc0e1d14e9b1.png)

**Comment by villaboamiguel** [comment]
Hola! 
Veo que emitiste 2 ahí ya o sea la comunicación con iFactura esta andando. Por favor cerrá el issue anterior en dicho caso.

Por este asunto, que error o mensaje te da en WHMCS que ves que no se emiten?

Gracias!

**Comment by Nexolife** [comment]
Cerrado el otro. Te comento que la factura me da un número de CAE que es para colocar en la AFIP y revisarla en dicho caso pero me dirijo al AFIP para revisar con el número de CAE y no me figura la factura en el AFIP, ese es el problema que estoy teniendo en este momento

**Comment by villaboamiguel** [comment]
Donde verificás esto? En que sección de AFIP?

https://help.wnpower.com/hc/es/articles/360031921392-Mis-comprobantes-emitidos-con-iFactura-no-aparecen-en-AFIP
En esta guia indica también que los comprobantes emitidos desde iFactura no figuran en AFIP de la misma manera que los comprobantes emitidos allá porque los de iFactura son realizados por un servicio web.

**Comment by Nexolife** [comment]
Te envío las imágenes de los pasos que realizo para ver las facturas (me disculpo por las fotos)

![WhatsApp Image 2021-02-24 at 11 08 31](https://user-images.githubusercontent.com/79521948/109012434-c658ab00-7690-11eb-93cc-21e5dbf263fd.jpeg)
![WhatsApp Image 2021-02-24 at 11 08 06](https://user-images.githubusercontent.com/79521948/109012442-c9539b80-7690-11eb-8945-59182f55d860.jpeg)
![WhatsApp Image 2021-02-24 at 11 07 49](https://user-images.githubusercontent.com/79521948/109012446-c9ec3200-7690-11eb-90bc-4e7c042d6b2e.jpeg)
![WhatsApp Image 2021-02-24 at 11 07 37](https://user-images.githubusercontent.com/79521948/109012452-cb1d5f00-7690-11eb-9e80-19b9ebcd42ef.jpeg)
![WhatsApp Image 2021-02-24 at 11 07 26](https://user-images.githubusercontent.com/79521948/109012454-cbb5f580-7690-11eb-83d1-0a532abddfbd.jpeg)

**Comment by villaboamiguel** [comment]
No hay problema con las fotos. Lo veo clarísimo.

En esa sección no vas a poder ver los comprobantes que se emiten con iFactura ya que el mismo utiliza un servicio web de AFIP. Los comprobantes que ves ahí son los generás desde la propia página de AFIP.

**Comment by Nexolife** [comment]
Okay, déjame entenderte. En pocas palabras me despreocupo porque ya todo está registrado aunque no aparezca las facturas en AFIP (web de ellos) ya que IFactura usa su servicio y no es necesario ingresar en la AFIP ya que están alojados en la sección comprobantes emitidos de IFactura. Correcto?

**Comment by villaboamiguel** [comment]
Tenes 2 vías para facturar:
* Comprobantes en lineá, en tu caso de responsable inscripto es RCEL. Que guarda la copia de los comprobantes en AFIP y quedan registrados.

* Web service: Que es para que un sistema se conecte a AFIP y pida autorización para emitir comprobantes. AFIP emite el CAE para esa autorización y esta correcta la factura en dicho caso. Este es el escenario de iFactura. No hay sección dentro de RCEL o comprobantes en lineá para ver el listado de comprobantes emitidos. Eso lo podes hacer desde iFactura con el articulo de Help que te envié previamente

**Comment by villaboamiguel** [comment]
Si la haces de iFactura o cualquier otro sistema que utilice un servicio web de AFIP, ahí no la vas a ver. 
Si la haces desde la página de AFIP mediante comprobantes en lineá si la vas a ver ahí.
