### ISSUE TITLE
Hipervínculo para ver mi Factura de AFIP en las notas

### ISSUE THREAD

**Issue by Nexolife** [wnpower/iFactura-WHMCS#8]
Hola quisiera colocar en la nota de los pedidos cuando compran un nuevo producto la factura. Hablé con el Soporte de WHMCS pero me dijeron que debía hablar con el soporte de iFactura para hacer esto. 
Te dejo un screen del ejemplo y de lo que me dijeron en el soporte de WHMCS
![WhatsApp Image 2021-02-24 at 12 13 01](https://user-images.githubusercontent.com/79521948/109207855-5decf500-7788-11eb-9f11-1a9eee056e48.jpeg)
![Captura de pantalla 2021-02-25 a las 4 42 57 p m](https://user-images.githubusercontent.com/79521948/109207989-88d74900-7788-11eb-83a6-b79fcc1e3124.png)

**Comment by villaboamiguel** [comment]
Hola!

Acá tenes los pasos para replicar esa modificación del template de WHMCS:
https://github.com/wnpower/iFactura-WHMCS#customizaciones

Los pasos ahí descriptos son para realizar sobre el template "six" de WHMCS que es con el que viene por defecto el sistema.

Saludos!

**Comment by Nexolife** [comment]
Hola hice cada uno de los pasos descriptos y no veo ningún efecto en mi Invoice

![Captura de pantalla 2021-02-26 a las 9 33 40 a m](https://user-images.githubusercontent.com/79521948/109300800-c3d38e00-7815-11eb-9613-3b4bbe7e81ab.png)

**Comment by villaboamiguel** [comment]
Corrobora estar trabajando en template que tengas activo en este momento para tu área de cliente. Además dicha modificación  solo se verá en el caso de que en el campo notas de la invoice se vea un texto como el siguiente:
`{{FacturaAFIP=806FEC5AF7F5B48B8A31A003A171F3FB}}`
Que es indicador de que tiene una factura asociada.

También puede ser una buena idea limpiar el cache de templates de WHMCS: Utilities -> System ->System Cleanup -> Empty Template Cache

Saludos
