### ISSUE TITLE
No factura clientes con TAX EXEPT

### ISSUE THREAD

**Issue by maxsarlija** [wnpower/iFactura-WHMCS#9]
Hola estoy con el siguiente inconveniente, utilizo WHCMS y tengo varios clientes libre de impuestos por lo cual tengo tildado TAX EXEMPT pero  El plugin no realiza facturas si el cliente tiene activado el campo "Tax Exempt" por eso no las puede facturar.
Para poder facturar hay que sacar el tilde.

Saben de alguna opcion para modificar esto?
Gracias!

**Comment by villaboamiguel** [comment]
Hola!

El plugin no factura a clientes que tenga tildado el campo "Tax Exempt". La única alternativa que hay es desactivar dicho campo para que el plugin reconozca dichas invoices.  Esto es así porque deberías facturar los mismos valores a todos los clientes. 

También podes hacer los comprobantes de forma manual desde https://app.ifactura.com.ar/

Saludos
